export const causes = [
  {
    id: 1,
    title: "Help João",
    short_description: "João needs urgent medical treatment.",
    description: "João was recently diagnosed with a serious condition that requires immediate medical attention. His family cannot afford the full cost of treatment, and time is critical.",
    about: "<p>João is an 8-year-old boy full of energy, curiosity, and big dreams. He loves playing soccer with his friends, drawing his favorite superheroes, and spending time laughing with his family. Like many kids his age, João should be enjoying school, games, and carefree moments. However, his life took an unexpected turn when he was diagnosed with a serious illness that requires continuous medical treatment and special care.</p><p>Since the diagnosis, João and his family have faced many challenges. Frequent hospital visits, medications, and procedures have become part of his routine. Despite everything, João remains brave and hopeful, always finding reasons to smile even on difficult days. His strength inspires everyone around him.</p><p>Unfortunately, the cost of treatment is very high, and his family is struggling to keep up with all the expenses. They are doing everything they can, but they cannot do it alone. With your support, João can continue his treatment, have access to the care he needs, and move closer to recovery.</p><p>Every contribution, no matter the amount, can make a real difference in João’s life. Your help can give him the chance to return to being a happy, healthy child — playing, learning, and dreaming about his future.</p>",
    goal: 10000,
    raised: 3500,
    image: "images/john.webp",
    category: "Health",
    verified: true,
    location: "Rio de Janeiro, Brazil",
    created: "2026-03-10",
    beneficiary: "João Silva"
  },
  {
    id: 2,
    title: "Food for Dona Rosa",
    short_description: "Fundraising to buy basic food supplies.",
    description: "Dona Rosa is facing financial hardship and needs help to secure basic food supplies for the coming months.",
    about: "<p>Dona Rosa is a retired elderly woman who lives alone and depends on a small pension that is no longer enough to cover her essential needs. With rising food prices, she has been struggling to maintain a basic diet. This campaign was created by neighbors who want to ensure she has access to nutritious meals and can live with dignity.</p>",
    goal: 2500,
    raised: 1300,
    image: "images/rose.webp",
    category: "Food",
    verified: false,
    location: "São Paulo, Brazil",
    created: "2026-02-25",
    beneficiary: "Dona Rosa"
  },
  {
    id: 3,
    title: "Carlos Surgery",
    short_description: "Urgent surgery to improve quality of life.",
    description: "Carlos requires a complex surgery that will significantly improve his quality of life and mobility.",
    about: "<p>Carlos Mendes is a 45-year-old worker who has been dealing with chronic pain for years due to a degenerative condition. Recently, doctors confirmed that surgery is the only viable solution. Without it, his condition will worsen, limiting his ability to work and support his family. This fundraiser seeks to cover hospital costs, post-surgery care, and rehabilitation.</p>",
    goal: 20000,
    raised: 8000,
    image: "images/carlos.webp",
    category: "Health",
    verified: true,
    location: "Belo Horizonte, Brazil",
    created: "2026-01-15",
    beneficiary: "Carlos Mendes"
  },
  {
    id: 4,
    title: "Support Hope Shelter",
    short_description: "Help maintain a children's shelter.",
    description: "Hope Shelter provides care and support for vulnerable children and needs help to continue its mission.",
    about: "<p>Hope Shelter is a non-profit organization that has been supporting children in vulnerable situations for over 10 years. They provide housing, education, and emotional support for dozens of kids who have been abandoned or come from unsafe environments. Due to recent funding cuts, the shelter is struggling to maintain its operations. This campaign aims to ensure the continuity of their essential work.</p>",
    goal: 15000,
    raised: 7000,
    image: "images/hope-shelter.webp",
    category: "Organization",
    verified: false,
    location: "Curitiba, Brazil",
    created: "2026-03-01",
    beneficiary: "Hope Shelter Institution"
  }
];